version: "3.9"

services:
  web:
    command: flask run --host=0.0.0.0 --port=8000   # ✅ override Gunicorn with Flask dev server
    environment:
      - FLASK_ENV=development                        # ✅ enables debug mode and auto-reload
      - FLASK_APP=run.py                            # ✅ entrypoint for your Flask app
      - OAUTHLIB_INSECURE_TRANSPORT=1 
    volumes:
      - .:/app                                       # ✅ mount code for instant updates
